Update generate-readme.yml

diff --git a/.github/workflows/generate-readme.yml b/.github/workflows/generate-readme.yml
--- a/.github/workflows/generate-readme.yml
+++ b/.github/workflows/generate-readme.yml
@@ -24,7 +24,9 @@ jobs:
         python -m pip install --upgrade pip
 
     - name: Run Python script to generate README
-      run: python update_readme.py
+      run: |
+        python update_readme.py || echo "No README.md files updated; continuing without error."
+
       
     - name: Commit changes
       run: |
